"""Alembic environment.

Supports three ways of being invoked:

* the runner passes a live ``Connection`` or ``Engine`` in ``config.attributes``
  (needed for in-memory SQLite in tests, where a second connection would see an
  empty database);
* the runner sets ``sqlalchemy.url``;
* plain ``alembic`` CLI with the URL from ``alembic.ini``.

``render_as_batch`` lets autogenerated migrations alter tables on SQLite.
"""

from __future__ import annotations

from logging.config import fileConfig

from alembic import context
from sqlalchemy import Connection, Engine, engine_from_config, pool

from victus.infrastructure.db.orm import Base

config = context.config
if config.config_file_name is not None and not config.attributes.get("skip_logging"):
    fileConfig(config.config_file_name)

target_metadata = Base.metadata


def _configure(connection: Connection) -> None:
    context.configure(
        connection=connection,
        target_metadata=target_metadata,
        render_as_batch=connection.dialect.name == "sqlite",
        compare_type=True,
    )


def run_migrations_offline() -> None:
    url = config.get_main_option("sqlalchemy.url")
    context.configure(
        url=url, target_metadata=target_metadata, literal_binds=True, render_as_batch=True
    )
    with context.begin_transaction():
        context.run_migrations()


def run_migrations_online() -> None:
    connectable = config.attributes.get("connection") or config.attributes.get("engine")
    if isinstance(connectable, Connection):
        _configure(connectable)
        with context.begin_transaction():
            context.run_migrations()
        return
    if not isinstance(connectable, Engine):
        connectable = engine_from_config(
            config.get_section(config.config_ini_section, {}),
            prefix="sqlalchemy.",
            poolclass=pool.NullPool,
        )
    with connectable.connect() as connection:
        _configure(connection)
        with context.begin_transaction():
            context.run_migrations()


if context.is_offline_mode():
    run_migrations_offline()
else:
    run_migrations_online()
