#!/usr/bin/env python
"""Generate ``docs/SCOPES.md``: every MCP tool and REST route against every scope profile.

The matrix is read from the code — the MCP registry (``victus.mcp.tools.TOOLS``), the route
table (``victus.api.scopes.ROUTE_SCOPES``) and the profiles
(``victus.application.scope_profiles.PROFILES``) — the same declarations the
scope-consistency tests hold against the use cases. A test fails when the committed file is
stale, so the page cannot drift from what the server enforces.

    uv run python scripts/scope_matrix.py           # rewrite docs/SCOPES.md
    uv run python scripts/scope_matrix.py --check   # exit 1 when it is stale
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
TARGET = ROOT / "docs" / "SCOPES.md"

if str(ROOT / "src") not in sys.path:  # runnable without an installed package
    sys.path.insert(0, str(ROOT / "src"))

from victus.api.scopes import ROUTE_SCOPES  # noqa: E402
from victus.application.scope_profiles import PROFILES, WORKER, ScopeProfile  # noqa: E402
from victus.application.tenant_context import SCOPE_APPROVE, Requires  # noqa: E402
from victus.mcp.tools import TOOLS, WORKER_TOOLS  # noqa: E402

YES = "yes"
NO = "—"


def _cell(requires: Requires, without_approve: str | None, profile: ScopeProfile) -> str:
    scopes = frozenset(profile.scopes)
    if not requires.allows_scopes(scopes):
        return NO
    if without_approve and SCOPE_APPROVE not in scopes:
        return without_approve
    return YES


def _row(cells: list[str]) -> str:
    return "| " + " | ".join(c.replace("|", "\\|") for c in cells) + " |"


def render() -> str:
    lines = [
        "# Scope matrix",
        "",
        "<!-- Generated by scripts/scope_matrix.py from the MCP registry, the REST route table "
        "and the scope profiles. Do not edit by hand: run "
        "`uv run python scripts/scope_matrix.py`. -->",
        "",
        "Which scope profile may call which MCP tool and REST route. The profiles, and what "
        "each one is for, are explained in [API.md → Scope profiles](API.md#scope-profiles); "
        "what each scope grants on its own is the scope table there.",
        "",
        "A cell reads:",
        "",
        f"- **{YES}** — the call is allowed and does what it says;",
        "- **proposal** — allowed, but without `approve` it is filed as a proposal a person "
        "decides (ADR 0013);",
        "- **draft** — allowed, but without `approve` the item arrives as a draft;",
        f"- **{NO}** — refused: the tool is not listed for that token, and a call anyway "
        "answers `forbidden` (MCP) or `403` (REST).",
        "",
        "*Requires* lists every scope the call needs: `a + b` means both, `(a or b)` either. "
        "A token holding `admin` passes every check.",
        "",
        "## Profiles",
        "",
        _row(["Profile", "Scopes"]),
        _row(["---", "---"]),
    ]
    for p in PROFILES:
        lines.append(_row([p.title, f"`{p.scope_list}`"]))
    lines += [
        "",
        "## MCP tools",
        "",
        f"The *{WORKER.title}* column also applies the worker's own tool list (`WORKER_TOOLS`): "
        "the worker holds the assistant's scopes but is handed fewer tools.",
        "",
    ]
    header = ["Tool", "Requires", *[p.title for p in PROFILES], "Note"]
    lines += [_row(header), _row(["---"] * len(header))]
    for spec in sorted(TOOLS, key=lambda t: t.name):
        cells = []
        for p in PROFILES:
            cell = _cell(spec.scope, spec.without_approve, p)
            if p is WORKER and spec.name not in WORKER_TOOLS:
                cell = NO
            cells.append(cell)
        lines.append(_row([f"`{spec.name}`", spec.scope.label(), *cells, spec.scope_note or ""]))
    rest_profiles = [p for p in PROFILES if p is not WORKER]
    lines += [
        "",
        "## REST routes",
        "",
        "Base path `/api/v1`. The worker calls no REST route, so it has no column here. Routes "
        "that need no scope — sign-in, `/health`, `/version`, a person's passkeys — are listed "
        "with their note; token management is described in API.md.",
        "",
    ]
    header = ["Route", "Requires", *[p.title for p in rest_profiles], "Note"]
    lines += [_row(header), _row(["---"] * len(header))]
    for key in sorted(ROUTE_SCOPES, key=lambda k: (k.split(" ", 1)[1], k.split(" ", 1)[0])):
        rs = ROUTE_SCOPES[key]
        if rs.public:
            cells = ["public"] * len(rest_profiles)
            requires = "none"
        elif not rs.requires.groups:
            cells = ["see note"] * len(rest_profiles)
            requires = "—"
        else:
            cells = [_cell(rs.requires, rs.without_approve, p) for p in rest_profiles]
            requires = rs.requires.label()
        lines.append(_row([f"`{key}`", requires, *cells, rs.note or ""]))
    lines.append("")
    return "\n".join(lines)


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--check", action="store_true", help="exit 1 when the file is stale")
    args = parser.parse_args(argv)
    text = render()
    current = TARGET.read_text(encoding="utf-8") if TARGET.exists() else ""
    if args.check:
        if current != text:
            print(f"{TARGET.relative_to(ROOT)} is stale: run scripts/scope_matrix.py")
            return 1
        print(f"{TARGET.relative_to(ROOT)} is current")
        return 0
    TARGET.write_text(text, encoding="utf-8", newline="\n")
    print(f"wrote {TARGET.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
