"""Repository ports.

The ports are typed against the persistence models re-exported by
``victus.infrastructure.db.orm`` because the application layer works with the
mapped entities directly (a pragmatic choice documented in ADR 0001: the
domain layer stays framework-free; the application layer may see mapped
objects). Only the signatures the use cases need are declared here.
"""

from __future__ import annotations

from collections.abc import Mapping, Sequence
from datetime import date, datetime
from typing import TYPE_CHECKING, Any, Protocol

from victus.domain.values import Macros, TrainingType

if TYPE_CHECKING:
    from victus.infrastructure.db import orm


class TenantRepository(Protocol):
    def get(self, tenant_id: str) -> orm.Tenant | None: ...

    def get_by_slug(self, slug: str) -> orm.Tenant | None: ...

    def add(self, tenant: orm.Tenant) -> orm.Tenant: ...

    def list(self) -> Sequence[orm.Tenant]: ...


class UserRepository(Protocol):
    def get(self, user_id: str) -> orm.User | None: ...

    def get_by_email(self, email: str) -> orm.User | None: ...

    def add(self, user: orm.User) -> orm.User: ...

    def list(self) -> Sequence[orm.User]: ...

    def add_passkey(self, credential: orm.PasskeyCredential) -> orm.PasskeyCredential: ...

    def passkey_by_credential_id(self, credential_id: bytes) -> orm.PasskeyCredential | None: ...

    def passkeys_for_user(self, user_id: str) -> Sequence[orm.PasskeyCredential]: ...

    def delete_passkey(self, credential: orm.PasskeyCredential) -> None: ...

    def add_session(self, session: orm.Session) -> orm.Session: ...

    def get_session(self, session_id: str) -> orm.Session | None: ...

    def delete_session(self, session_id: str) -> None: ...

    def add_token(self, token: orm.ApiToken) -> orm.ApiToken: ...

    def token_by_hash(self, token_hash: str) -> orm.ApiToken | None: ...

    def tokens(self) -> Sequence[orm.ApiToken]: ...


class ProductRepository(Protocol):
    def get(self, product_id: int) -> orm.Product | None: ...

    def get_consumable(self, consumable_id: int) -> orm.Consumable | None: ...

    def add(self, product: orm.Product) -> orm.Product: ...

    def add_product(self, name: str, **fields: object) -> orm.Product: ...

    def add_ad_hoc(self, item: orm.AdHocItem) -> orm.AdHocItem: ...

    def add_ad_hoc_item(self, name: str, **fields: object) -> orm.AdHocItem: ...

    def list(self, *, category_id: int | None = None) -> Sequence[orm.Product]: ...

    def search(self, query: str, limit: int = 20) -> Sequence[orm.Product]: ...

    def by_external_ref(self, external_ref: str) -> orm.Product | None: ...

    def by_name(self, name: str) -> orm.Product | None: ...

    def all_names(self) -> Sequence[tuple[int, str]]: ...

    def portions_for(self, product_id: int) -> Sequence[orm.Portion]: ...

    def add_portion(self, portion: orm.Portion) -> orm.Portion: ...

    def get_portion(self, portion_id: int) -> orm.Portion | None: ...

    def delete_portion(self, portion: orm.Portion) -> None: ...

    def delete_consumable(self, consumable: orm.Consumable) -> None: ...

    def display_hints_for(
        self, product_ids: Sequence[int]
    ) -> dict[int, tuple[str | None, str | None]]: ...

    def category_names_for(self, product_ids: Sequence[int]) -> dict[int, str]: ...

    def categories(self) -> Sequence[orm.Category]: ...

    def category_by_name(self, name: str) -> orm.Category | None: ...

    def add_category(self, category: orm.Category) -> orm.Category: ...

    def units(self) -> Sequence[orm.Unit]: ...

    def unit(self, code: str) -> orm.Unit | None: ...


class RecipeRepository(Protocol):
    def get(self, recipe_id: int) -> orm.Recipe | None: ...

    def by_name(self, name: str) -> orm.Recipe | None: ...

    def add(self, recipe: orm.Recipe) -> orm.Recipe: ...

    def list(self) -> Sequence[orm.Recipe]: ...

    def add_batch(self, batch: orm.RecipeBatch) -> orm.RecipeBatch: ...

    def add_recipe_batch(
        self, recipe: orm.Recipe, name: str, **fields: object
    ) -> orm.RecipeBatch: ...

    def batches_for(self, recipe_id: int) -> Sequence[orm.RecipeBatch]: ...

    def get_batch(self, batch_id: int) -> orm.RecipeBatch | None: ...


class DayLogRepository(Protocol):
    def get(self, day_log_id: int) -> orm.DayLog | None: ...

    def get_by_date(self, day: date) -> orm.DayLog | None: ...

    def add(self, day_log: orm.DayLog) -> orm.DayLog: ...

    def list(
        self,
        start: date | None = None,
        end: date | None = None,
        status: str | None = None,
    ) -> Sequence[orm.DayLog]: ...

    def macros_for(self, day: date) -> Macros | None: ...

    def macros_between(self, start: date, end: date) -> dict[date, Macros]: ...

    def countable_days(
        self, start: date | None = None, end: date | None = None
    ) -> Sequence[date]: ...

    def add_meal(self, meal: orm.Meal) -> orm.Meal: ...

    def get_meal(self, meal_id: int) -> orm.Meal | None: ...

    def delete_meal(self, meal: orm.Meal) -> None: ...

    def add_line_item(self, item: orm.LineItem) -> orm.LineItem: ...

    def get_line_item(self, item_id: int) -> orm.LineItem | None: ...

    def delete_line_item(self, item: orm.LineItem) -> None: ...

    def line_item_macros(self, day: date) -> dict[int, Macros]: ...

    def usage_of(self, consumable_id: int, limit: int = 100) -> Sequence[Mapping[str, Any]]: ...

    def draft_days(self) -> Sequence[orm.DayLog]: ...

    def delete_day(self, day_log: orm.DayLog) -> None: ...


class WeightRepository(Protocol):
    def add(self, entry: orm.WeightEntry) -> orm.WeightEntry: ...

    def get(self, entry_id: int) -> orm.WeightEntry | None: ...

    def list(
        self, start: date | None = None, end: date | None = None
    ) -> Sequence[orm.WeightEntry]: ...

    def by_measured_at(self, measured_at: datetime) -> orm.WeightEntry | None: ...

    def delete(self, entry: orm.WeightEntry) -> None: ...

    def daily_means(
        self, start: date | None = None, end: date | None = None
    ) -> dict[date, float]: ...


class TargetBandRepository(Protocol):
    def get(self, band_id: int) -> orm.TargetBand | None: ...

    def add(self, band: orm.TargetBand) -> orm.TargetBand: ...

    def list(self) -> Sequence[orm.TargetBand]: ...

    def for_date(self, day: date, training_type: TrainingType | None) -> orm.TargetBand | None: ...


class SettingsRepository(Protocol):
    def current(self) -> orm.TenantSettings | None: ...

    def for_date(self, day: date) -> orm.TenantSettings | None: ...

    def versions(self) -> Sequence[orm.TenantSettings]: ...

    def add_version(
        self, data: dict[str, Any], valid_from: date, changed_by: str | None
    ) -> orm.TenantSettings: ...


class CaptureRepository(Protocol):
    def get(self, capture_id: str) -> orm.Capture | None: ...

    def add(self, capture: orm.Capture) -> orm.Capture: ...

    def by_hash(self, content_hash: str) -> orm.Capture | None: ...

    def list(
        self,
        status: str | None = None,
        target_date: date | None = None,
        limit: int | None = None,
        product_id: int | None = None,
    ) -> Sequence[orm.Capture]: ...

    def add_attachment(self, attachment: orm.Attachment) -> orm.Attachment: ...

    def get_attachment(self, attachment_id: str) -> orm.Attachment | None: ...

    def attachment_by_hash(self, sha256: str) -> orm.Attachment | None: ...

    def add_transcript(self, transcript: orm.Transcript) -> orm.Transcript: ...

    def transcript_for(self, capture_id: str) -> orm.Transcript | None: ...

    def delete(self, capture: orm.Capture) -> None: ...

    def attachment_refs(self, attachment_id: str) -> int: ...

    def delete_attachment(self, attachment: orm.Attachment) -> None: ...

    def discarded_before(self, cutoff: datetime) -> Sequence[orm.Capture]: ...


class ProposalRepository(Protocol):
    def add(self, proposal: orm.ProductProposal) -> orm.ProductProposal: ...

    def get(self, proposal_id: str) -> orm.ProductProposal | None: ...

    def list(
        self, status: str | None = None, product_id: int | None = None, limit: int = 200
    ) -> Sequence[orm.ProductProposal]: ...


class AgentRepository(Protocol):
    def add_run(self, run: orm.AgentRun) -> orm.AgentRun: ...

    def get_run(self, run_id: str) -> orm.AgentRun | None: ...

    def list_runs(self, limit: int = 50) -> Sequence[orm.AgentRun]: ...

    def queued_runs(self) -> Sequence[orm.AgentRun]: ...

    def add_session(self, session: orm.AgentSession) -> orm.AgentSession: ...

    def sessions_for(self, run_id: str) -> Sequence[orm.AgentSession]: ...

    def try_acquire_lock(
        self, day: date, runner: str, run_id: str, ttl_minutes: int, now: datetime
    ) -> bool: ...

    def lock_holder(self, day: date, now: datetime) -> orm.AgentLock | None: ...

    def extend_lock(self, day: date, run_id: str, ttl_minutes: int, now: datetime) -> bool: ...

    def list_runs_by_status(self, status: str) -> Sequence[orm.AgentRun]: ...

    def release_locks(self, run_id: str) -> int: ...

    def release_lock(self, day: date) -> bool: ...

    def locks(self) -> Sequence[orm.AgentLock]: ...


class DayMessageRepository(Protocol):
    def add(self, message: orm.DayMessage) -> orm.DayMessage: ...

    def thread(self, day: date) -> Sequence[orm.DayMessage]: ...


class SnapshotRepository(Protocol):
    def add(self, snapshot: orm.ReportSnapshot) -> orm.ReportSnapshot: ...

    def get(self, snapshot_id: str) -> orm.ReportSnapshot | None: ...

    def list(
        self, report_name: str | None = None, status: str | None = None, limit: int = 50
    ) -> Sequence[orm.ReportSnapshot]: ...

    def delete(self, snapshot: orm.ReportSnapshot) -> None: ...


class AuditRepository(Protocol):
    def add(self, entry: orm.AuditLog) -> orm.AuditLog: ...

    def record(
        self, action: str, target_type: str, target_id: str, diff: dict[str, object] | None = None
    ) -> orm.AuditLog: ...

    def for_target(self, target_type: str, target_id: str) -> Sequence[orm.AuditLog]: ...


class BackupJobRepository(Protocol):
    def add(self, job: orm.BackupJob) -> orm.BackupJob: ...

    def get(self, job_id: str) -> orm.BackupJob | None: ...

    def list(self, limit: int = 50) -> Sequence[orm.BackupJob]: ...

    def latest_finished(self) -> orm.BackupJob | None: ...
